---
platform: linux
inputs:
- name: git-repo
caches:
- path: gradle
params:
  BRANCH:
  CI: true
  GRADLE_ENTERPRISE_ACCESS_KEY:
  GRADLE_ENTERPRISE_CACHE_USERNAME:
  GRADLE_ENTERPRISE_CACHE_PASSWORD:
  GRADLE_ENTERPRISE_URL: https://ge.spring.io
run:
  path: bash
  args:
    - -ec
    - |
      ${PWD}/git-repo/ci/scripts/build-pr.sh
